contact_links:
    - name: Feature request
      url: https://github.com/orgs/primefaces/discussions/categories/primevue-lab
      about: Propose an enhancement at discussions.
    - name: Support
      url: https://primevue-lab.org/support/
      about: Professional support for the open source innovation.
